name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 当 push 到 main 分支时触发部署

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 将 templates 文件复制到 output 目录。
      - name: Build static site
        run: |
          mkdir -p output
          cp -r templates/* output/  # Copy the contents of templates to output

      # 使用 peaceiris/actions-gh-pages 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
